---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-hello-world-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            namespace: dev
          - name: staging
            namespace: staging
          - name: prod
            namespace: prod

  template:
    metadata:
      name: hos-argocd-{{name}}
    spec:
      project: default
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/IliaDiv/hos-argocd.git
        targetRevision: HEAD
        path: kubernetes/Home-Office-Store
        helm:
          valueFiles:
            - ../../environment/{{namespace}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
