{
 "title": "Home-Office-Store",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values({job=\"backend-svc\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) by (node) / \r\n  sum(kube_node_status_allocatable{resource=\"cpu\"}) by (node) * 100",
     "legendFormat": "Node: {{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"backend-svc\", namespace=~\"$namespace\"})",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{job=\"backend-svc\", namespace=~\"$namespace\"})",
     "legendFormat": "Virtual Memory Used"
    },
    {
     "expr": "sum(sum by (pod) (container_memory_usage_bytes{namespace=~\"$namespace\"}))",
     "legendFormat": "Total Container Memory Usage"
    }
   ]
  },
  {
   "title": "React CPU Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{container=\"react-frontend\", namespace=~\"$namespace\"}[$__range]) / \r\n  rate(container_cpu_cfs_periods_total{container=\"react-frontend\", namespace=~\"$namespace\"}[$__range]) * 100",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Flask CPU Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{container=\"flask-backend\", namespace=~\"$namespace\"}[$__range]) / \r\n  rate(container_cpu_cfs_periods_total{container=\"flask-backend\", namespace=~\"$namespace\"}[$__range]) * 100",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "N8N CPU Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{container=\"n8n\", namespace=~\"$namespace\"}[$__range]) / \r\n  rate(container_cpu_cfs_periods_total{container=\"n8n\", namespace=~\"$namespace\"}[$__range]) * 100",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "React Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{container=\"react-frontend\",namespace=~\"$namespace\"} / \r\n  container_memory_max_usage_bytes{container=\"react-frontend\",namespace=~\"$namespace\"}) * 100",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Flask Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{container=\"flask-backend\",namespace=~\"$namespace\"} / \r\n  container_memory_max_usage_bytes{container=\"flask-backend\",namespace=~\"$namespace\"}) * 100",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "N8N  Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{container=\"n8n\",namespace=~\"$namespace\"} / \r\n  container_memory_max_usage_bytes{container=\"n8n\",namespace=~\"$namespace\"}) * 100",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  { "title": "flask", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Max Process Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " max(time() - process_start_time_seconds{job=\"backend-svc\",namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "description": "both 400+ and 500+ errors",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(http_request_total{job=\"backend-svc\", namespace=~\"$namespace\",status_code=~\"4..\"}[$__range]) or vector(0)) + sum(increase(http_request_total{job=\"backend-svc\",namespace=~\"$namespace\", status_code=~\"5..\"}[$__range]) or vector(0))) / sum(increase(http_request_total{job=\"backend-svc\", namespace=~\"$namespace\",}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path, status_code) (\r\n  rate(http_request_total{job=\"backend-svc\", namespace=~\"$namespace\"}[$__range])\r\n)",
     "legendFormat": "Path: {{path}}, Status: {{status_code}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{job=\"backend-svc\",namespace=~\"$namespace\"}[$__range])) / sum(rate(flask_http_request_duration_seconds_count{job=\"backend-svc\",namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in Progress",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (http_requests_in_progress{job=\"backend-svc\", namespace=~\"$namespace\", path!=\"/metrics\"}) > 1 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(http_request_total{job=\"backend-svc\", namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{job=\"backend-svc\", namespace=~\"$namespace\"}[$__range])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"backend-svc\", namespace=~\"$namespace\"} / process_max_fds{job=\"backend-svc\", namespace=~\"$namespace\"} ",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  { "title": "n8n", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Max Process Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " max(time() - n8n_process_start_time_seconds{job=\"n8n-svc\",namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min Active Workflows",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(n8n_active_workflow_count{job=\"n8n-svc\",namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "n8n_process_open_fds{job=\"n8n-svc\", namespace=~\"$namespace\"} / n8n_process_max_fds{job=\"n8n-svc\", namespace=~\"$namespace\"}",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "Old Space",
   "type": "timeseries",
   "description": "Memory leakage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(n8n_nodejs_heap_space_size_used_bytes{space=\"old\", job=\"n8n-svc\",namespace=~\"$namespace\"} / n8n_nodejs_heap_space_size_total_bytes{space=\"old\", job=\"n8n-svc\",namespace=~\"$namespace\"}) * 100",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "JS GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(n8n_nodejs_gc_duration_seconds_count{job=\"n8n-svc\", namespace=~\"$namespace\", kind=\"major\"}[$__range])\r\n",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(n8n_nodejs_gc_duration_seconds_sum{job=\"n8n-svc\", namespace=~\"$namespace\", kind=\"major\"}[$__range])\r\n/\r\nrate(n8n_nodejs_gc_duration_seconds_count{job=\"n8n-svc\", namespace=~\"$namespace\", kind=\"major\"}[$__range])",
     "legendFormat": "Pod: {{pod}}"
    }
   ]
  },
  {
   "title": "GC Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(n8n_nodejs_gc_duration_seconds_count{job=\"n8n-svc\", namespace=~\"$namespace\"}[$__range])",
     "legendFormat": "Pod: {{pod}}, Kind: {{kind}}"
    }
   ]
  }
 ]
}